# Generated by Django 5.0.7 on 2024-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(default="Default Name", max_length=255),
        ),
    ]
