# Generated by Django 5.0.7 on 2024-07-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("difficulty", models.CharField(max_length=50)),
                ("categories", models.JSONField()),
            ],
        ),
    ]
