# Generated by Django 5.0.7 on 2024-07-12 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_problem"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("input", models.TextField()),
                ("expected_output", models.TextField()),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.problem"
                    ),
                ),
            ],
        ),
    ]
