# Generated by Django 5.0.7 on 2024-07-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="language",
            field=models.CharField(default="C++", max_length=50),
            preserve_default=False,
        ),
    ]
