# Generated by Django 5.0.7 on 2024-07-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_submission_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="time_limit",
            field=models.IntegerField(default=1000),
        ),
    ]
