# Generated by Django 5.0.7 on 2024-07-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_problem_time_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="time_limit",
            field=models.IntegerField(default=2),
        ),
    ]
